#ifndef FILEIOPLUGIN_GLOBAL_H
#define FILEIOPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILEIOPLUGIN_LIBRARY)
#  define FILEIOPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILEIOPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEIOPLUGIN_GLOBAL_H
